Feat/seeker home 2
beyond-io/roo.me pull request #184
Opened 2021-05-16 11:37 UTC by nadavsu

# PR Dependencies
**Depends on #160
Depends on #176
Depends on #181**

# Description
- Created the front-end of the seeker's homepage.
- Enhanced the sidebar: added a user image and a welcome message
- Created apartment/roommate cards that load automatically with the page
- Routed the page to the backend of the web-app

## Screenshots
![Screen Shot 2021-05-16 at 11 15 23](https://user-images.githubusercontent.com/53123142/118394099-487ebd00-b64b-11eb-9a90-3295d097c481.png)

![Screen Shot 2021-05-16 at 11 15 39](https://user-images.githubusercontent.com/53123142/118394106-50d6f800-b64b-11eb-9b96-9049326dfd58.png)

### Issues closed by this PR
Fixes #182

2021-05-18 14:05 UTC, tamirho commented
WOW!!

2021-05-18 14:55 UTC, Micha546 reviewed
🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 
Looks GREAT!

2021-05-19 08:11 UTC, DanielMy777 commented
Good job!!
Looks like this needs a rebase so I'll review after that's done

2021-05-19 12:53 UTC, AmitAharoni commented
Looking amazing!

2021-05-19 12:53 UTC, AmitAharoni approved these changes

2021-05-19 13:20 UTC, tamirho requested changes

2021-05-19 13:20 UTC, tamirho commented on main/views.py
>              function that will render the homepage for the owner.'''
Please add here a call to the owner_home view

2021-05-19 13:39 UTC, tamirho commented on main/views.py
>              function that will render the homepage for the owner.'''
Nevermind.. resolved in #193

2021-05-19 13:39 UTC, tamirho approved these changes

2021-05-20 11:01 UTC, AmitAharoni commented
@nadavsu 
Please rebase :)

2021-05-20 11:30 UTC, merged