Alter sidebar - DO NOT MERGE BEFORE #226
beyond-io/roo.me pull request #229
Opened 2021-05-21 13:31 UTC by Micha546

# Description
Moving the side bar to the base_template

Now we can see the side bar in all the pages.
Added an empty sidebar tag in apartment_register and seeker_register
So there will be no sidebar there.
Deleted home.html as it is no longer in use

## Screenshots
![image](https://user-images.githubusercontent.com/79044795/119144818-b5ca8d80-ba51-11eb-8e18-ac4388d77d02.png)
![image](https://user-images.githubusercontent.com/79044795/119144844-bf53f580-ba51-11eb-954f-0ffebdf12745.png)

### Issues closed by this PR
Fix #228

### PR Dependencies
Depended on #226

2021-05-21 13:41 UTC, DanielMy777 approved these changes
Considering you checked and this works
LGTM

2021-05-21 16:59 UTC, nadavsu commented
In the images, the side bar has no name.
It says "Welcome, !". It should say the user's name though.

2021-05-21 17:01 UTC, nadavsu commented
Also, you need to rebase here I think.

2021-05-21 18:37 UTC, DanielMy777 requested changes

2021-05-21 18:37 UTC, DanielMy777 commented on main/templates/main/base_template.html
> +              <h5 class="card-title username">Welcome, {{seeker.first_name}}!</h5>
Switch this to `{{user.first_name}}`

2021-05-22 07:19 UTC, DanielMy777 approved these changes
LGTM

2021-05-22 07:20 UTC, merged

2021-05-22 07:20 UTC, nadavsu reviewed
Nice.