Add new base template with navbar
beyond-io/roo.me pull request #87
Opened 2021-04-27 21:28 UTC by nadavsu

The base template divides a page into four main parts:
1. The title marked with {% block title %}
2. The navbar items marked with {% block navbar %}
3. The content marked with {% block content %}
4. The footer marked with {% block footer %}

It also contains the bootstrap script/library.
Every page inheriting this template will have a navigation bar.

2021-04-28 06:06 UTC, 1Oreo approved these changes

2021-04-28 08:08 UTC, tamirho commented
LGTM

2021-04-28 10:01 UTC, DanielMy777 reviewed
Nice looking navbar!

2021-04-28 15:20 UTC, tamirho approved these changes

2021-04-28 15:20 UTC, tamirho commented on main/templates/main/base_template.html
> +  </footer>
I think that footer tag should be inside a body tag. Correct me if I'm wrong.

2021-04-29 10:52 UTC, simzacks requested changes

2021-04-29 10:52 UTC, simzacks commented on main/templates/main/base_template.html
> +  </footer>
I Agree.  The footer probably won't show up if it's out of the body.
See: https://www.w3schools.com/tags/tag_footer.asp

2021-04-29 21:00 UTC, simzacks approved these changes

2021-04-29 21:47 UTC, Omeramsc requested changes
This change doesn't pass the CI; it won't get reviewed or merged until it will.

2021-04-30 12:48 UTC, nadavsu commented
Had to merge with roo.me/master, works now.

2021-04-30 13:05 UTC, merged

2021-05-02 14:15 UTC, AmitAharoni commented
Thats great!